language: python
python: -3.6
before_install:
- openssl aes-256-cbc -K $encrypted_b80b5b01c5ce_key -iv $encrypted_b80b5b01c5ce_iv
install: "-pip install -r requirements.txt"
before_script: "-cd instagram"
script: "-python manage.py test"
