branch-defaults:
  deploy:
    environment: instagram-project-dev
    group_suffix: null
global:
  application_name: instagram_project
  branch: null
  default_ec2_keyname: EB-User
  default_platform: Docker 17.06.2-ce
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
